AlphaBlog_v3/config/routes.rb
Rails.application.routes.draw do
  resources :articles
  
  get 'welcome/index'
  root 'welcome#index'

end

AlphaBlog_v3/app/models/article.rb
class Article < ActiveRecord::Base
  
  
end

AlphaBlog_v3/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    @article = Article.new
  end
  
  def index
    @articles = Article.all
  end
  
  def create
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Der Artikel wurde erfolgreich erstellt"
      redirect_to articles_path(@article)      
    else
      render 'new'
    end
    
    def show
      @article = Article.find(params[:id])
    end
    
  end
  
  private
  def article_params
    params.require(:article).permit(:title, :description)
  end 
end

AlphaBlog_v3/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

AlphaBlog_v3/app/helpers/welcome_helper.rb
module WelcomeHelper
end

AlphaBlog_v3/app/views/articles/index.html.erb
<h1>Listing articles</h1>
 
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th></th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to 'Show', article_path(article) %></td>
    </tr>
  <% end %>
</table>

AlphaBlog_v3/app/views/articles/new.html.erb
<h1>Create an article</h1>

<% if @article.errors.any? %>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
   </ul>
  <% end %>
<% end %>


<%= form_for @article do |f| %>
  <p>
    <%= f.label :title %>   <br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :text %>   <br>
    <%= f.text_area :text %>
  </p>
  <p>
    <%= f.submit %>   
  </p>
<% end %>

AlphaBlog_v3/app/views/articles/show.html.erb
<h1>Showing selected article</h1>

<strong>Title:</strong>
  <%= @article.title %>
</p>
  
<p> 
  Title: <%= @article.title %>
</p> 

<p> 
  Description: <%= @article.description %>
</p> 

AlphaBlog_v3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlogV3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% flash.each do |name, msg| %>
    <ul>
      <li><%= msg %></li>
    </ul>
  <% end %>
  
<%= yield %>

</body>
</html>

AlphaBlog_v3/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>